[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++23","-fdiagnostics-color=always", "-Wall", "-g", "-fsanitize=address,undefined", "-ftrapv", "-O2"]
# "-fsanitize=address,undefined", "-ftrapv" をつけると行列が遅くなるので外した。