[[languages.cpp.environments]]
CXX = "g++"

[[languages.cpp.environments]]
CXX = "clang++"
CXXFLAGS = ["-std=c++23","-fdiagnostics-color=always", "-Wall", "-g", "-fsanitize=address,undefined", "-ftrapv", "-D_GLIBCXX_DEBUG"]